import requests

DRUID_HOST = "http://druid.dev.ssa.triplelift.net"
# DRUID_HOST = "http://druid.prod.ssa.triplelift.net"

LOOKUPS_TO_DELETE = [
    "active_brands_lookup_druid",
    "advertiser_lookup_druid",
    "app_name_lookup_druid",
    "auction_result_phase_one_ext_lookup_druid",
    "auction_status_lookup_druid",
    "bid_type_lookup_druid",
    "booked_revenue_type_lookup_druid",
    "brand_to_ad_category_lookup_druid",
    "brand_to_an_ad_category_lookup_druid",
    "branded_content_campaign_lookup_druid",
    "branded_content_instance_url_lookup_druid",
    "branded_content_link_lookup_druid",
    "branded_content_medium_lookup_druid",
    "browser_lookup_druid",
    "content_category_id_lookup_druid",
    "content_category_lookup_druid",
    "country_code_to_sector_name_lookup_druid",
    "country_id_to_sector_id_lookup_druid",
    "country_id_to_sector_name_lookup_druid",
    "creative_asset_caption_lookup_druid",
    "creative_asset_description_lookup_druid",
    "creative_asset_heading_lookup_druid",
    "creative_asset_image_lookup_druid",
    "creative_category_lookup_druid",
    "creative_library_lookup_druid",
    "data_center_region_lookup_druid",
    "dco_vendor_lookup_druid",
    "deal_active_lookup_druid",
    "deal_code_lookup_druid",
    "deal_end_date_lookup_druid",
    "deal_id_to_bid_floor_lookup_druid",
    "deal_id_to_created_by_user_id_lookup_druid",
    "deal_id_to_deal_price_type_lookup_druid",
    "deal_id_to_deal_spend_type_id_lookup_druid",
    "deal_id_to_deleted_lookup_druid",
    "deal_id_to_discount_lookup_druid",
    "deal_id_to_is_marketplace_lookup_druid",
    "deal_id_to_is_pmp_lookup_druid",
    "deal_id_to_last_modified_by_user_id_lookup_druid",
    "deal_id_to_last_modified_lookup_druid",
    "deal_id_to_margin_lookup_druid",
    "deal_id_to_primary_goal_id_lookup_druid",
    "deal_id_to_secondary_goal_id_lookup_druid",
    "deal_id_to_time_created_lookup_druid",
    "deal_parent_name_lookup_druid",
    "deal_priority_lookup_druid",
    "deal_rejection_lookup_druid",
    "deal_start_date_lookup_druid",
    "deal_type_id_lookup_druid",
    "device_type_lookup_druid",
    "dma_lookup_druid",
    "domain_and_masked_domain_lookup_druid",
    "domain_id_to_mobile_app_bundle_lookup_druid",
    "domain_lookup_druid",
    "domain_name_to_mobile_app_bundle_lookup_druid",
    "engagement_event_lookup_druid",
    "format_lookup_druid",
    "geo_target_region_lookup_druid",
    "guaranteed_outcomes_event_type_lookup_druid",
    "high_viewability_lookup_druid",
    "impression_supply_lookup_druid",
    "insertion_order_budget_lookup_druid",
    "insertion_order_end_date_lookup_druid",
    "insertion_order_lookup_druid",
    "insertion_order_start_date_lookup_druid",
    "inventory_control_id_lookup_druid",
    "inventory_control_type_lookup_druid",
    "io_added_value_lookup_druid",
    "io_id_to_account_manager_id_lookup_druid",
    "io_id_to_account_manager_name_lookup_druid",
    "line_item_budget_lookup_druid",
    "line_item_end_date_lookup_druid",
    "line_item_lookup_druid",
    "line_item_start_date_lookup_druid",
    "margin_adjustment_type_lookup_druid",
    "margin_type_lookup_druid",
    "member_tier_lookup_druid",
    "mobile_app_bundle_code_lookup_druid",
    "mobile_app_bundle_lookup_druid",
    "non_app_domain_lookup_druid",
    "non_mobile_domain_lookup_druid",
    "os_lookup_druid",
    "owner_lookup_druid",
    "parent_brand_id_lookup_druid",
    "parent_brand_name_lookup_druid",
    "placement_ad_category_lookup_druid",
    "pmp_flag_lookup_druid",
    "publisher_member_lookup_druid",
    "region_lookup_druid",
    "renderer_lookup_druid",
    "reserve_price_lookup_druid",
    "seller_member_id_lookup_druid",
    "ssai_vendor_lookup_druid",
    "supply_type_name_lookup_druid",
    "tactic_brand_lookup_druid",
    "tactic_budget_lookup_druid",
    "tactic_end_date_lookup_druid",
    "tactic_start_date_lookup_druid",
    "template_name_lookup_druid"
]

def delete(host, endpoint, lookup_id):
    url = f"{host}/{endpoint}/{lookup_id}"
    response = requests.delete(url)
    if response.status_code == 202:
        print(f"Deleted lookup: {lookup_id}")
    else:
        print(f"Failed to delete {lookup_id}: {response.status_code} {response.text}")

for lookup_id in LOOKUPS_TO_DELETE:
    delete(host=DRUID_HOST, endpoint="druid/coordinator/v1/lookups/config/__default", lookup_id=lookup_id)